import type { ModelEntry } from "@lucky/shared"

export const OPENAI_MODELS: ModelEntry[] = [
  {
    gateway: "openai-api",
    gatewayModelId: "gpt-5-codex",
    input: 1.25,
    output: 10,
    cachedInput: 0.125,
    contextLength: 400000,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsVision: false,
    supportsReasoning: true,
    supportsAudio: false,
    supportsVideo: false,
    speed: "balanced",
    intelligence: 9,
    pricingTier: "medium",
    runtimeEnabled: false,
    uiHiddenInProd: true,
  },

  {
    gateway: "openai-api",
    gatewayModelId: "gpt-5",
    input: 1.25,
    output: 10,
    cachedInput: 0.125,
    contextLength: 400000,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsVision: true,
    supportsReasoning: true,
    supportsAudio: false,
    supportsVideo: false,
    speed: "balanced",
    intelligence: 9,
    pricingTier: "medium",
    runtimeEnabled: true,
  },

  {
    gateway: "openai-api",
    gatewayModelId: "gpt-5-chat",
    input: 1.25,
    output: 10,
    cachedInput: 0.125,
    contextLength: 128000,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsVision: false,
    supportsReasoning: false,
    supportsAudio: false,
    supportsVideo: false,
    speed: "fast",
    intelligence: 9,
    pricingTier: "medium",
    runtimeEnabled: true,
  },

  {
    gateway: "openai-api",
    gatewayModelId: "gpt-5-mini",
    input: 0.25,
    output: 2,
    cachedInput: 0.025,
    contextLength: 400000,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsVision: true,
    supportsReasoning: false,
    supportsAudio: false,
    supportsVideo: false,
    speed: "fast",
    intelligence: 8,
    pricingTier: "low",
    runtimeEnabled: true,
  },

  {
    gateway: "openai-api",
    gatewayModelId: "gpt-5-nano",
    input: 0.05,
    output: 0.4,
    cachedInput: 0.005,
    contextLength: 400000,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsVision: false,
    supportsReasoning: false,
    supportsAudio: false,
    supportsVideo: false,
    speed: "fast",
    intelligence: 7,
    pricingTier: "low",
    runtimeEnabled: true,
  },

  // o-series (Reasoning Models)
  {
    gateway: "openai-api",
    gatewayModelId: "o1-pro",
    input: 150,
    output: 600,
    cachedInput: null,
    contextLength: 200000,
    supportsTools: false,
    supportsJsonMode: false,
    supportsStreaming: true,
    supportsVision: false,
    supportsReasoning: true,
    supportsAudio: false,
    supportsVideo: false,
    speed: "slow",
    intelligence: 10,
    pricingTier: "high",
    runtimeEnabled: false,
    uiHiddenInProd: true,
  },

  {
    gateway: "openai-api",
    gatewayModelId: "o3-pro",
    input: 20,
    output: 80,
    cachedInput: null,
    contextLength: 200000,
    supportsTools: false,
    supportsJsonMode: false,
    supportsStreaming: true,
    supportsVision: false,
    supportsReasoning: true,
    supportsAudio: false,
    supportsVideo: false,
    speed: "slow",
    intelligence: 10,
    pricingTier: "high",
    runtimeEnabled: false,
    uiHiddenInProd: true,
  },

  {
    gateway: "openai-api",
    gatewayModelId: "o1",
    input: 15,
    output: 60,
    cachedInput: 7.5,
    contextLength: 200000,
    supportsTools: false,
    supportsJsonMode: false,
    supportsStreaming: true,
    supportsVision: false,
    supportsReasoning: true,
    supportsAudio: false,
    supportsVideo: false,
    speed: "slow",
    intelligence: 10,
    pricingTier: "high",
    runtimeEnabled: false,
    uiHiddenInProd: true,
  },

  {
    gateway: "openai-api",
    gatewayModelId: "o3",
    input: 2,
    output: 8,
    cachedInput: 0.5,
    contextLength: 200000,
    supportsTools: false,
    supportsJsonMode: false,
    supportsStreaming: true,
    supportsVision: false,
    supportsReasoning: true,
    supportsAudio: false,
    supportsVideo: false,
    speed: "balanced",
    intelligence: 9,
    pricingTier: "medium",
    runtimeEnabled: false,
    uiHiddenInProd: true,
  },

  {
    gateway: "openai-api",
    gatewayModelId: "o4-mini-high",
    input: 1.1,
    output: 4.4,
    cachedInput: 0.275,
    contextLength: 200000,
    supportsTools: false,
    supportsJsonMode: false,
    supportsStreaming: true,
    supportsVision: false,
    supportsReasoning: true,
    supportsAudio: false,
    supportsVideo: false,
    speed: "balanced",
    intelligence: 8,
    pricingTier: "low",
    runtimeEnabled: true,
  },

  {
    gateway: "openai-api",
    gatewayModelId: "o4-mini",
    input: 1.1,
    output: 4.4,
    cachedInput: 0.275,
    contextLength: 200000,
    supportsTools: false,
    supportsJsonMode: false,
    supportsStreaming: true,
    supportsVision: false,
    supportsReasoning: true,
    supportsAudio: false,
    supportsVideo: false,
    speed: "balanced",
    intelligence: 8,
    pricingTier: "low",
    runtimeEnabled: false,
    uiHiddenInProd: true,
  },

  {
    gateway: "openai-api",
    gatewayModelId: "o3-mini-high",
    input: 1.1,
    output: 4.4,
    cachedInput: 0.55,
    contextLength: 200000,
    supportsTools: false,
    supportsJsonMode: false,
    supportsStreaming: true,
    supportsVision: false,
    supportsReasoning: true,
    supportsAudio: false,
    supportsVideo: false,
    speed: "balanced",
    intelligence: 8,
    pricingTier: "low",
    runtimeEnabled: false,
    uiHiddenInProd: true,
  },

  {
    gateway: "openai-api",
    gatewayModelId: "o3-mini",
    input: 1.1,
    output: 4.4,
    cachedInput: 0.55,
    contextLength: 200000,
    supportsTools: false,
    supportsJsonMode: false,
    supportsStreaming: true,
    supportsVision: false,
    supportsReasoning: true,
    supportsAudio: false,
    supportsVideo: false,
    speed: "balanced",
    intelligence: 8,
    pricingTier: "low",
    runtimeEnabled: false,
    uiHiddenInProd: true,
  },

  {
    gateway: "openai-api",
    gatewayModelId: "o1-mini",
    input: 1.1,
    output: 4.4,
    cachedInput: 0.55,
    contextLength: 128000,
    supportsTools: false,
    supportsJsonMode: false,
    supportsStreaming: true,
    supportsVision: false,
    supportsReasoning: true,
    supportsAudio: false,
    supportsVideo: false,
    speed: "balanced",
    intelligence: 8,
    pricingTier: "low",
    runtimeEnabled: false,
    uiHiddenInProd: true,
  },

  {
    gateway: "openai-api",
    gatewayModelId: "o1-mini-2024-09-12",
    input: 1.1,
    output: 4.4,
    cachedInput: 0.55,
    contextLength: 128000,
    supportsTools: false,
    supportsJsonMode: false,
    supportsStreaming: true,
    supportsVision: false,
    supportsReasoning: true,
    supportsAudio: false,
    supportsVideo: false,
    speed: "balanced",
    intelligence: 8,
    pricingTier: "low",
    runtimeEnabled: false,
    uiHiddenInProd: true,
  },

  {
    gateway: "openai-api",
    gatewayModelId: "codex-mini",
    input: 1.5,
    output: 6,
    cachedInput: 0.375,
    contextLength: 200000,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsVision: false,
    supportsReasoning: false,
    supportsAudio: false,
    supportsVideo: false,
    speed: "fast",
    intelligence: 8,
    pricingTier: "medium",
    runtimeEnabled: false,
    uiHiddenInProd: true,
  },

  // GPT-4.1 Series
  {
    gateway: "openai-api",
    gatewayModelId: "gpt-4.1",
    input: 2,
    output: 8,
    cachedInput: 0.5,
    contextLength: 1047576,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsVision: false,
    supportsReasoning: false,
    supportsAudio: false,
    supportsVideo: false,
    speed: "balanced",
    intelligence: 8,
    pricingTier: "medium",
    runtimeEnabled: false,
    uiHiddenInProd: true,
  },

  {
    gateway: "openai-api",
    gatewayModelId: "gpt-4.1-mini",
    input: 0.4,
    output: 1.6,
    cachedInput: 0.1,
    contextLength: 1047576,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsVision: false,
    supportsReasoning: false,
    supportsAudio: false,
    supportsVideo: false,
    speed: "fast",
    intelligence: 7,
    pricingTier: "low",
    runtimeEnabled: false,
    uiHiddenInProd: true,
  },

  {
    gateway: "openai-api",
    gatewayModelId: "gpt-4.1-nano",
    input: 0.1,
    output: 0.4,
    cachedInput: 0.025,
    contextLength: 1047576,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsVision: false,
    supportsReasoning: false,
    supportsAudio: false,
    supportsVideo: false,
    speed: "fast",
    intelligence: 6,
    pricingTier: "low",
    runtimeEnabled: false,
    uiHiddenInProd: true,
  },

  // GPT-4o Series
  {
    gateway: "openai-api",
    gatewayModelId: "gpt-4o-audio-preview",
    input: 2.5,
    output: 10,
    cachedInput: 1.25,
    contextLength: 128000,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsVision: false,
    supportsReasoning: false,
    supportsAudio: true,
    supportsVideo: false,
    speed: "balanced",
    intelligence: 8,
    pricingTier: "medium",
    runtimeEnabled: false,
    uiHiddenInProd: true,
  },

  {
    gateway: "openai-api",
    gatewayModelId: "gpt-4o",
    input: 2.5,
    output: 10,
    cachedInput: 1.25,
    contextLength: 128000,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsVision: true,
    supportsReasoning: false,
    supportsAudio: false,
    supportsVideo: false,
    speed: "balanced",
    intelligence: 8,
    pricingTier: "medium",
    runtimeEnabled: false,
    uiHiddenInProd: true,
  },

  {
    gateway: "openai-api",
    gatewayModelId: "gpt-4o-2024-11-20",
    input: 2.5,
    output: 10,
    cachedInput: 1.25,
    contextLength: 128000,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsVision: true,
    supportsReasoning: false,
    supportsAudio: false,
    supportsVideo: false,
    speed: "balanced",
    intelligence: 8,
    pricingTier: "medium",
    runtimeEnabled: false,
    uiHiddenInProd: true,
  },

  {
    gateway: "openai-api",
    gatewayModelId: "gpt-4o-2024-08-06",
    input: 2.5,
    output: 10,
    cachedInput: 1.25,
    contextLength: 128000,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsVision: true,
    supportsReasoning: false,
    supportsAudio: false,
    supportsVideo: false,
    speed: "balanced",
    intelligence: 8,
    pricingTier: "medium",
    runtimeEnabled: false,
    uiHiddenInProd: true,
  },

  {
    gateway: "openai-api",
    gatewayModelId: "gpt-4o-2024-05-13",
    input: 5,
    output: 15,
    cachedInput: null,
    contextLength: 128000,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsVision: true,
    supportsReasoning: false,
    supportsAudio: false,
    supportsVideo: false,
    speed: "balanced",
    intelligence: 8,
    pricingTier: "medium",
    runtimeEnabled: false,
    uiHiddenInProd: true,
  },

  {
    gateway: "openai-api",
    gatewayModelId: "chatgpt-4o-latest",
    input: 5,
    output: 15,
    cachedInput: null,
    contextLength: 128000,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsVision: true,
    supportsReasoning: false,
    supportsAudio: false,
    supportsVideo: false,
    speed: "balanced",
    intelligence: 8,
    pricingTier: "medium",
    runtimeEnabled: false,
    uiHiddenInProd: true,
  },

  {
    gateway: "openai-api",
    gatewayModelId: "gpt-4o-mini",
    input: 0.15,
    output: 0.6,
    cachedInput: 0.075,
    contextLength: 128000,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsVision: true,
    supportsReasoning: false,
    supportsAudio: false,
    supportsVideo: false,
    speed: "fast",
    intelligence: 7,
    pricingTier: "low",
    runtimeEnabled: false,
    uiHiddenInProd: true,
  },

  {
    gateway: "openai-api",
    gatewayModelId: "gpt-4o-mini-2024-07-18",
    input: 0.15,
    output: 0.6,
    cachedInput: 0.075,
    contextLength: 128000,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsVision: true,
    supportsReasoning: false,
    supportsAudio: false,
    supportsVideo: false,
    speed: "fast",
    intelligence: 7,
    pricingTier: "low",
    runtimeEnabled: false,
    uiHiddenInProd: true,
  },

  {
    gateway: "openai-api",
    gatewayModelId: "gpt-4o-mini-search-preview",
    input: 0.15,
    output: 0.6,
    cachedInput: null,
    contextLength: 128000,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsVision: true,
    supportsReasoning: false,
    supportsAudio: false,
    supportsVideo: false,
    speed: "fast",
    intelligence: 7,
    pricingTier: "low",
    runtimeEnabled: false,
    uiHiddenInProd: true,
  },

  {
    gateway: "openai-api",
    gatewayModelId: "gpt-4o-search-preview",
    input: 2.5,
    output: 10,
    cachedInput: null,
    contextLength: 128000,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsVision: true,
    supportsReasoning: false,
    supportsAudio: false,
    supportsVideo: false,
    speed: "balanced",
    intelligence: 8,
    pricingTier: "medium",
    runtimeEnabled: false,
    uiHiddenInProd: true,
  },

  // GPT-4 Series
  {
    gateway: "openai-api",
    gatewayModelId: "gpt-4-turbo",
    input: 10,
    output: 30,
    cachedInput: null,
    contextLength: 128000,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsVision: true,
    supportsReasoning: false,
    supportsAudio: false,
    supportsVideo: false,
    speed: "balanced",
    intelligence: 8,
    pricingTier: "high",
    runtimeEnabled: false,
    uiHiddenInProd: true,
  },

  {
    gateway: "openai-api",
    gatewayModelId: "gpt-4-turbo-preview",
    input: 10,
    output: 30,
    cachedInput: null,
    contextLength: 128000,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsVision: true,
    supportsReasoning: false,
    supportsAudio: false,
    supportsVideo: false,
    speed: "balanced",
    intelligence: 8,
    pricingTier: "high",
    runtimeEnabled: false,
    uiHiddenInProd: true,
  },

  {
    gateway: "openai-api",
    gatewayModelId: "gpt-4-1106-preview",
    input: 10,
    output: 30,
    cachedInput: null,
    contextLength: 128000,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsVision: false,
    supportsReasoning: false,
    supportsAudio: false,
    supportsVideo: false,
    speed: "balanced",
    intelligence: 8,
    pricingTier: "high",
    runtimeEnabled: false,
    uiHiddenInProd: true,
  },

  {
    gateway: "openai-api",
    gatewayModelId: "gpt-4",
    input: 30,
    output: 60,
    cachedInput: null,
    contextLength: 8191,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsVision: false,
    supportsReasoning: false,
    supportsAudio: false,
    supportsVideo: false,
    speed: "slow",
    intelligence: 8,
    pricingTier: "high",
    runtimeEnabled: false,
    uiHiddenInProd: true,
  },

  {
    gateway: "openai-api",
    gatewayModelId: "gpt-4-0314",
    input: 30,
    output: 60,
    cachedInput: null,
    contextLength: 8191,
    supportsTools: true,
    supportsJsonMode: false,
    supportsStreaming: true,
    supportsVision: false,
    supportsReasoning: false,
    supportsAudio: false,
    supportsVideo: false,
    speed: "slow",
    intelligence: 8,
    pricingTier: "high",
    runtimeEnabled: false,
    uiHiddenInProd: true,
  },

  // GPT-3.5 Series
  {
    gateway: "openai-api",
    gatewayModelId: "gpt-3.5-turbo",
    input: 0.5,
    output: 1.5,
    cachedInput: null,
    contextLength: 16385,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsVision: false,
    supportsReasoning: false,
    supportsAudio: false,
    supportsVideo: false,
    speed: "fast",
    intelligence: 6,
    pricingTier: "low",
    runtimeEnabled: false,
    uiHiddenInProd: true,
  },

  {
    gateway: "openai-api",
    gatewayModelId: "gpt-3.5-turbo-16k",
    input: 3,
    output: 4,
    cachedInput: null,
    contextLength: 16385,
    supportsTools: true,
    supportsJsonMode: true,
    supportsStreaming: true,
    supportsVision: false,
    supportsReasoning: false,
    supportsAudio: false,
    supportsVideo: false,
    speed: "fast",
    intelligence: 6,
    pricingTier: "low",
    runtimeEnabled: false,
    uiHiddenInProd: true,
  },

  {
    gateway: "openai-api",
    gatewayModelId: "gpt-3.5-turbo-instruct",
    input: 1.5,
    output: 2,
    cachedInput: null,
    contextLength: 4095,
    supportsTools: false,
    supportsJsonMode: false,
    supportsStreaming: true,
    supportsVision: false,
    supportsReasoning: false,
    supportsAudio: false,
    supportsVideo: false,
    speed: "fast",
    intelligence: 6,
    pricingTier: "low",
    runtimeEnabled: false,
    uiHiddenInProd: true,
  },
]
