export const LoggingTypes = {
  standard: {
    Setup: false,
    Tools: false,
    Memory: false,
    InvocationPipeline: false,
    Messaging: false,
    ValidationBeforeHandoff: false,
    Improvement: true,
    Summary: false,
    Database: false,
    GP: false,
    API: false,
  },
  verbose: {
    Setup: true,
    Tools: true,
    Memory: true,
    InvocationPipeline: true,
    Messaging: true,
    Improvement: true,
    Summary: true,
    Database: true,
    GP: true,
    API: false,
  },
  custom: {
    Setup: true,
    Tools: false,
    Memory: false,
    InvocationPipeline: false,
    Messaging: false,
    Improvement: true,
    Summary: false,
    Database: true,
    GP: false,
    API: true,
  },
} as const
