# DISABLED - MCP Server Image Deploy workflow (kept for reference)
# This workflow was moved from packages/mcp-server/.github/workflows/
# It is currently disabled and will not run

name: Deploy Images to GHCR

env:
  DOTNET_VERSION: '6.0.x'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  push-image:
    if: false  # DISABLED
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v3

      - name: 'Build Service Image'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.service
          push: true
          tags: ghcr.io/lucky/lucky-mcp-server:latest
          cache-from: type=registry,ref=ghcr.io/lucky/lucky-mcp-server:latest
          cache-to: type=inline

