name: tests-badge

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

permissions:
  contents: write

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run core unit tests (JSON)
        working-directory: core
        run: bun test --reporter=json > ../vitest-results.json || true

      - name: Generate tests badge
        run: node .github/scripts/generate-tests-badge.mjs

      - name: Commit badge if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        env:
          HUSKY: 0
        with:
          commit_message: "chore(ci): update tests badge"
          file_pattern: docs/badges/tests.svg
          commit_options: "--no-verify"
